name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Add permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./HydraulicGradient/HydraulicGradient.csproj

      - name: Build
        run: dotnet build ./HydraulicGradient/HydraulicGradient.csproj --no-restore

      - name: Publish
        run: dotnet publish ./HydraulicGradient/HydraulicGradient.csproj -c Release -o release --nologo

      - name: Update base href for GitHub Pages
        run: |
          if [ -f "release/wwwroot/index.html" ]; then
            sed -i 's|<base href="/hydraulicgradient/" />|<base href="/HydraulicGradient/" />|g' release/wwwroot/index.html
            echo "Updated base href in index.html"
          else
            echo "index.html not found in expected location"
            ls -la release/wwwroot/
          fi

      - name: Copy index.html to 404.html
        run: |
          if [ -f "release/wwwroot/index.html" ]; then
            cp release/wwwroot/index.html release/wwwroot/404.html
            echo "Created 404.html"
          else
            echo "Could not create 404.html - index.html not found"
          fi

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4